Vagrant.configure('2') do |config|
#  config.vm.box = 'trusty64'
#  config.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'
  config.vm.box = 'precise64'
  config.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box'

  config.vm.provision :ansible do |ansible|
    ansible.playbook = '../playbook_appdev.yml'
    ansible.extra_vars = { ansible_ssh_user: 'vagrant', vagrant: true }

    ansible.verbose = 'v'
  end
end
